### ISSUE TITLE
Next 관련 질문입니다.

### ISSUE THREAD

**Issue by rhs0266** [snu-sf-class/pp201602-hw-06#1]
biIter에서 Next를 data의 길이보다 훨씬 많은 회수를 반복한 다음에, 마지막으로 Prev를 하면 마지막 원소가 나와야 하는지 None이 나와야 하는 지 궁금합니다.

**Comment by alxest** [comment]
pp201602에 다시 올려주시겠어요?

**Comment by alxest** [comment]
다른 학생들도 볼 수 있는게 좋으니까요
